package My_package;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//import com.mycompany.airsea.AdminFunctions;
//import static com.mycompany.airsea.Login.connection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author shamsalotaibi
 */
public class AddFlight extends javax.swing.JFrame {

    /**
     * Creates new form AddFlight
     */
    public AddFlight() {
        initComponents();
    }
    
 final String DATABASE_URL = "jdbc:mysql://localhost:3306/dlr";
 
    static Connection con = null;
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        destCombo = new javax.swing.JComboBox<>();
        arrCombo = new javax.swing.JComboBox<>();
        classCombo = new javax.swing.JComboBox<>();
        deptime = new javax.swing.JTextField();
        arrtime = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        apCombo = new javax.swing.JComboBox<>();
        dep1 = new javax.swing.JTextField();
        dep2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dep3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        arr1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        arr2 = new javax.swing.JTextField();
        arr3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add flight on D.L.R airplane");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Add Flight:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Destination:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Arrival:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Class:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Departure Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Arrival Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Departure Time:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Arrival Time:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Flight Price:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        destCombo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        destCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dammam", "Riyadh", "Jeddah", "Medina", "Al-Ahsa", "Al-'Ula", "Yanbu", "Buraidah" }));
        destCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destComboActionPerformed(evt);
            }
        });
        jPanel1.add(destCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        arrCombo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arrCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dammam", "Riyadh", "Jeddah", "Medina", "Al-Ahsa", "Al-'Ula", "Yanbu", "Buraidah" }));
        arrCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrComboActionPerformed(evt);
            }
        });
        jPanel1.add(arrCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        classCombo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        classCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "FirstClass" }));
        classCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classComboActionPerformed(evt);
            }
        });
        jPanel1.add(classCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        deptime.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        deptime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptimeActionPerformed(evt);
            }
        });
        jPanel1.add(deptime, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, 30));

        arrtime.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arrtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrtimeActionPerformed(evt);
            }
        });
        jPanel1.add(arrtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 30));

        price.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 110, 30));

        Submit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Submit.setForeground(new java.awt.Color(0, 0, 102));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 90, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Airplane:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel12.setText("    /");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 40, 20));

        apCombo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        apCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AirPlane A220", "Airplane E321", "Airplane 750Q", "Airplane DZ-1", "750AirBus", "Airplane W70", "AirBus-MM1" }));
        jPanel1.add(apCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 140, 20));

        dep1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        dep1.setText("yyyy");
        dep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep1ActionPerformed(evt);
            }
        });
        jPanel1.add(dep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 50, 30));

        dep2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        dep2.setText("mm");
        jPanel1.add(dep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 40, 30));

        jLabel13.setText("  /");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 20, -1));

        dep3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        dep3.setText("dd");
        jPanel1.add(dep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 40, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Back");
        jButton1.setMaximumSize(new java.awt.Dimension(84, 27));
        jButton1.setMinimumSize(new java.awt.Dimension(84, 27));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, 30));

        arr1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arr1.setText("yyyy");
        arr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arr1ActionPerformed(evt);
            }
        });
        jPanel1.add(arr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 50, 30));

        jLabel16.setText("    /");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 40, 20));

        arr2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arr2.setText("mm");
        jPanel1.add(arr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 40, 30));

        arr3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        arr3.setText("dd");
        jPanel1.add(arr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 40, 30));

        jLabel17.setText("  /");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 20, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_package/background1.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        try{
       con = DriverManager.getConnection(DATABASE_URL,"root","");
        PreparedStatement ps1 = con.prepareStatement("SELECT * FROM AIRPLANE WHERE TYPE =?");
        PreparedStatement ps2 = con.prepareStatement("INSERT INTO FLIGHT (FLIGHT_PRICE,DEP_DATE,DEP_TIME,ARR_DATE,ARR_TIME, DEP_CITY,ARR_CITY, AirP_RegNO, CLASS) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?)") ;
        ResultSet rs1;
        int regno=0;
        
        String type=apCombo.getSelectedItem().toString();
        
        ps1.setString(1, type);
       
        
        rs1=ps1.executeQuery();
        
            if (rs1.next()) {
                
                regno=rs1.getInt("REG_NO");
                
                
            }
        
        ps2.setDouble(1, Double.valueOf(price.getText()));
        String depdate= dep1.getText()+"-"+dep2.getText()+"-"+dep3.getText();
                
        ps2.setString(2,depdate);
        ps2.setString(3,deptime.getText());
       String arrdate= arr1.getText()+"-"+arr2.getText()+"-"+arr3.getText();
        
        ps2.setString(4,arrdate);
        ps2.setString(5,arrtime.getText());
        ps2.setString(6, String.valueOf(destCombo.getSelectedItem().toString()));
        ps2.setString(7, String.valueOf(arrCombo.getSelectedItem().toString()));
        ps2.setString(8, String.valueOf(regno));
        ps2.setString(9, String.valueOf(classCombo.getSelectedItem().toString()));
        
        
        
      ps2.executeUpdate();
       
       
        
       
       JOptionPane.showMessageDialog(null, "ADDED Successfully!");

       
       rs1.close();
       ps1.close();
       ps2.close();
       con.close();
        
        
        
        
        }
        
               
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void destComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destComboActionPerformed

    private void arrComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrComboActionPerformed

    private void dep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dep1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        AdminFunctions n= new  AdminFunctions();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void arr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arr1ActionPerformed

    private void deptimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptimeActionPerformed

    private void arrtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrtimeActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void classComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> apCombo;
    private javax.swing.JTextField arr1;
    private javax.swing.JTextField arr2;
    private javax.swing.JTextField arr3;
    private javax.swing.JComboBox<String> arrCombo;
    private javax.swing.JTextField arrtime;
    private javax.swing.JComboBox<String> classCombo;
    private javax.swing.JTextField dep1;
    private javax.swing.JTextField dep2;
    private javax.swing.JTextField dep3;
    private javax.swing.JTextField deptime;
    private javax.swing.JComboBox<String> destCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
